---

- hosts: all
  gather_facts: true            
  tasks: []                    

- hosts: bastion-ubuntu       
  gather_facts: false
  become: true             
  run_once: true

  vars:
    exporters:
      - { name: node_exporter, port: 9100 }
      - { name: sql_exporter,  port: 9399 }
    output_dir: /etc/prometheus/file_sd
    prometheus_user: prometheus
    prometheus_group: prometheus

  tasks:
    - name: debug per-host facts
      debug:
        msg: "host={{ item }} ip={{ hostvars[item].ansible_default_ipv4.address }}"
      loop: "{{ groups['all'] }}"

    - name: build all_targets list
      set_fact:
        all_targets: "{{ groups['all']
                         | map('extract', hostvars)
                         | map('json_query', '{ip: ansible_default_ipv4.address, hostname: inventory_hostname}')
                         | list }}"


    - debug:
        var: all_targets


    - file:
        path: "{{ output_dir }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'

    - name: render {{ item.name }}.json
      template:
        src: file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.name }}.json"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'
      loop: "{{ exporters }}"
      vars:
        targets: "{{ all_targets }}"
        exporter_port: "{{ item.port }}"

    - name: cat rendered file
      shell: cat {{ output_dir }}/{{ item.name }}.json | jq .
      register: rendered
      loop: "{{ exporters }}"
      changed_when: false
    - debug: var=rendered.stdout_lines
