---
- hosts: bastion           
  gather_facts: false
  become: true               
  vars:
    exporters:
      - { name: node_exporter, port: 9100 }
      - { name: sql_exporter,  port: 9399 }
    output_dir: /etc/prometheus/file_sd
    prometheus_user: prometheus
    prometheus_group: prometheus

  pre_tasks:
    - name: get facts
      delegate_to: "{{ item }}"
      setup:
      loop: "{{ groups['shardman'] }}"
      run_once: true

    - name: perform list all_targets
      set_fact:
        all_targets: []
    - set_fact:
        all_targets: "{{ all_targets + [ {'ip': hostvars[item]['ansible_default_ipv4']['address'], 'hostname': item} ] }}"
      loop: "{{ groups['shardman'] }}"
      run_once: true

  tasks:
    - file:
        path: "{{ output_dir }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'

    - template:
        src: file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.name }}.json"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'
      loop: "{{ exporters }}"
      vars:
        targets: "{{ all_targets }}"
        exporter_port: "{{ item.port }}"
