---
- name: Собрать IP и hostname с хостов
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Регистрируем IP и hostname
      set_fact:
        host_sd_info: "{{ host_sd_info | default([]) + [ {'ip': ansible_default_ipv4.address, 'hostname': ansible_hostname} ] }}"
      delegate_to: localhost
      run_once: true

- name: Генерация Prometheus file_sd конфигов
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    exporters:
      - name: node_exporter
        port: 9100
      - name: sql_exporter
        port: 9399
    output_dir: /etc/prometheus/file_sd
    prometheus_owner: prometheus
    prometheus_group: prometheus

  tasks:
    - name: Создать файл для каждого экспортера
      template:
        src: templates/file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.name }}.json"
        owner: "{{ prometheus_owner }}"
        group: "{{ prometheus_group }}"
        mode: '0644'
      loop: "{{ exporters }}"
      vars:
        host_data: "{{ host_sd_info }}"
