---
- name: Collect IP + hostname on every host
  hosts: all
  gather_facts: true
  tasks:
    - set_fact:
        exporter_targets:
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ inventory_hostname }}"

- name: Build Prometheus file_sd JSON on bastion            
  gather_facts: false
  vars:   
    exporters:
      - { name: node_exporter, port: 9100 }
      - { name: sql_exporter,  port: 9399 }
    output_dir: /etc/prometheus/file_sd
    prometheus_user: prometheus
    prometheus_group: prometheus
  tasks:
    - set_fact:
        all_targets: "{{ groups['all'] | map('extract', hostvars, 'exporter_targets') | list }}"

    - name: Render JSON files
      become: true
      delegate_to: 185.86.146.169
      template:
        src: file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.name }}.json"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'
      loop: "{{ exporters }}"
      vars:
        targets: "{{ all_targets }}"
        exporter_port: "{{ item.port }}"
