---
- name: Собираем IP и hostname с хостов
  hosts: all
  gather_facts: true
  tasks:
    - name: Формируем список нужных данных
      set_fact:
        collected_hosts: "{{ collected_hosts | default([]) + [ {'ip': ansible_default_ipv4.address, 'hostname': ansible_hostname} ] }}"
      delegate_to: localhost
      run_once: true

- name: Генерируем конфиги Prometheus на бастионе
  hosts: localhost
  gather_facts: false
  vars:
    exporters:
      - job: node_exporter
        port: 9100
        file: node_exporter.json
      - job: sql_exporter
        port: 9399
        file: sql_exporter.json
    output_dir: /etc/prometheus/file_sd

  tasks:
    - name: Убедимся, что директория есть
      become: yes
      file:
        path: "{{ output_dir }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Генерим файлы для экспортеров
      template:
        src: templates/file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.file }}"
        owner: prometheus
        group: prometheus
        mode: '0644'
      loop: "{{ exporters }}"
      loop_control:
        label: "{{ item.file }}"
      vars:
        hosts: "{{ hostvars['localhost']['collected_hosts'] }}"
        port: "{{ item.port }}"
        job: "{{ item.job }}"
