---
- name: Gather target facts
  hosts: all
  gather_facts: true

- name: Generate Prometheus file_sd configs on bastion
  hosts: localhost
  gather_facts: false
  vars:
    exporters:
      - job: node_exporter
        port: 9100
        file: node_exporter.json
      - job: sql_exporter
        port: 9399
        file: sql_exporter.json
    output_dir: /etc/prometheus/file_sd

  tasks:
    - name: Collect host data
      set_fact:
        all_targets_data: >-
          {{
            groups['all'] | map('extract', hostvars) | map('extract', ['ansible_default_ipv4', 'address']) |
            zip(groups['all'] | map('extract', hostvars) | map(attribute='ansible_hostname')) |
            map('community.general.dict_kv', ['ip', 'hostname']) | list
          }}
      run_once: true

    - name: Build targets for each exporter
      set_fact:
        exporter_targets: "{{ exporter_targets | default({}) | combine({ item.job: {
          'file': item.file,
          'targets': (
            all_targets_data | map('combine', {
              'targets': [ (target.ip ~ ':' ~ item.port) ],
              'labels': {
                'ip': target.ip,
                'hostname': target.hostname,
                'job': item.job
              }
            })
          | list )
        }}) }}"
      loop: "{{ exporters }}"
      loop_control:
        loop_var: item
      vars:
        # чтобы не ловить ошибку с undefined
        all_targets_data: "{{ all_targets_data | default([]) }}"
        target: "{{ item0 }}"
      with_items: "{{ exporters }}"
      loop_control:
        loop_var: item
        label: "{{ item.job }}"
      delegate_to: localhost
      run_once: true

    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Write file_sd JSON files
      template:
        src: templates/file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.value.file }}"
        owner: prometheus
        group: prometheus
        mode: '0644'
      loop: "{{ exporter_targets | dict2items }}"
