---
- name: Собираем факты с удалённых хостов
  hosts: all
  gather_facts: true

- name: Формируем file_sd конфиги на бастионе
  hosts: localhost
  gather_facts: false
  vars:
    exporters:
      - job: node_exporter
        port: 9100
        file: node_exporter.json
      - job: sql_exporter
        port: 9399
        file: sql_exporter.json
    output_dir: /etc/prometheus/file_sd

  tasks:
    - name: Собираем список хостов
      set_fact:
        target_list: >-
          {{
            groups['all'] | map('extract', hostvars) | map('combine', {
              'ip': attribute('ansible_default_ipv4.address'),
              'hostname': attribute('ansible_hostname')
            }) | list
          }}
      run_once: true

    - name: Убедимся, что директория существует
      file:
        path: "{{ output_dir }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Шаблонизируем файл для каждого экспортера
      template:
        src: templates/file_sd.j2
        dest: "{{ output_dir }}/{{ item.file }}"
        owner: prometheus
        group: prometheus
        mode: '0644'
      loop: "{{ exporters }}"
      loop_control:
        label: "{{ item.file }}"
      vars:
        port: "{{ item.port }}"
        job: "{{ item.job }}"
        hosts: "{{ target_list }}"
