---
- name: generate file node_exporter1
  hosts: all             
  become: yes
  serial: 1                

  vars:
    exporters:
      - { name: node_exporter, port: 9100 }
      - { name: sql_exporter,  port: 9399 }
    output_dir: /etc/prometheus/file_sd
    prometheus_user: prometheus
    prometheus_group: prometheus

  tasks:

    # ---------- Регистрируем target в Prometheus ----------
    - name: Render node_exporter SD file
      template:
        src: node_exporter.json.j2
        dest: /etc/prometheus/file_sd/node_exporter1.json
        owner: prometheus
        group: prometheus
        mode: "0644"
      loop: "{{ exporters }}"  
      delegate_to: 185.86.146.169
      become: yes
