---
- hosts: shardman
  gather_facts: true
  tasks:
    - set_fact:
        exporter_meta:
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ inventory_hostname }}"

- hosts: bastion
  gather_facts: false
  become: true       
  vars:
    exporters:
      - { name: node_exporter, port: 9100 }
      - { name: sql_exporter,  port: 9399 }
    output_dir: /etc/prometheus/file_sd
    prometheus_user: prometheus
    prometheus_group: prometheus
  tasks:
    - set_fact:
        all_targets: "{{ groups['all'] | map('extract', hostvars, 'exporter_meta') | list }}"

    - file:
        path: "{{ output_dir }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'

    - template:
        src: file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.name }}.json"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'
      loop: "{{ exporters }}"
      vars:
        targets: "{{ all_targets }}"
        exporter_port: "{{ item.port }}"
