---
- name: Собрать данные с хостов
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Сохраняем IP и hostname каждого хоста
      set_fact:
        collected_hosts: "{{ collected_hosts | default([]) + [ { 'ip': ansible_default_ipv4.address, 'hostname': inventory_hostname } ] }}"
      run_once: true
      delegate_to: localhost

- name: Сгенерировать file_sd файлы на бастионе
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    exporters:
      - name: node_exporter
        port: 9100
      - name: sql_exporter
        port: 9399
    output_dir: /etc/prometheus/file_sd
    prometheus_user: prometheus
    prometheus_group: prometheus
  tasks:
    - name: Генерируем файл для каждого экспортера
      template:
        src: templates/file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.name }}.json"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'
      loop: "{{ exporters }}"
      vars:
        host_list: "{{ hostvars.localhost.collected_hosts }}"
