---
- name: Gather target facts
  hosts: all
  gather_facts: true

- name: Generate Prometheus file_sd configs on bastion
  hosts: localhost
  gather_facts: false
  vars:
    exporters:
      - job: node_exporter
        port: 9100
        file: node_exporter.json
      - job: sql_exporter
        port: 9399
        file: sql_exporter.json
    output_dir: /etc/prometheus/file_sd

  tasks:
    - name: Collect host data from all hosts
      set_fact:
        targets_data: "{{ targets_data | default([]) + [ {
          'ip': hostvars[item].ansible_default_ipv4.address,
          'hostname': hostvars[item].ansible_hostname
        } ] }}"
      loop: "{{ groups['all'] }}"
      loop_control:
        loop_var: item
      run_once: true

    - name: Initialize exporter_targets structure
      set_fact:
        exporter_targets: "{{ dict(exporters | map(attribute='job') | zip(exporters | map('combine', {'targets': []}))) }}"

    - name: Fill exporter_targets with targets
      set_fact:
        exporter_targets: >-
          {{
            exporter_targets | combine({
              exporter.job: {
                'file': exporter.file,
                'targets': targets_data | map('combine', {
                  'targets': [ item.ip ~ ':' ~ exporter.port ],
                  'labels': {
                    'ip': item.ip,
                    'hostname': item.hostname,
                    'job': exporter.job
                  }
                }) | list
              }
            }, recursive=True)
          }}
      loop: "{{ exporters }}"
      loop_control:
        loop_var: exporter
      vars:
        # переопределяем item внутри map(), чтобы избежать коллизий с loop_var
        targets_data: "{{ targets_data }}"
        item: "{{ item }}"  # костыль, чтоб внутри map работало — Ansible странно себя ведёт без этого

    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Render JSON files for each exporter
      template:
        src: templates/file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.value.file }}"
        owner: prometheus
        group: prometheus
        mode: '0644'
      loop: "{{ exporter_targets | dict2items }}"
