---
- name: generate file node_exporter1
  hosts: all             
  become: yes
  serial: 1                

  vars:
    # ====== Node Exporter ======
    node_exporter_version: "1.9.1"
    node_exporter_user: "node_exporter"
    node_exporter_bin_dir: "/usr/local/bin"
    node_exporter_unit: "/etc/systemd/system/node_exporter.service"

    # ====== Prometheus (на AWX-хосте) ======
    prometheus_config: "/etc/prometheus/prometheus.yml"
    prometheus_service: "prometheus"

    # autodetect arch: x86_64 → amd64, aarch64 → arm64, иначе armv7
    node_exporter_arch: >-
      {{ 'amd64'  if ansible_architecture == 'x86_64'  else
         'arm64'  if ansible_architecture == 'aarch64' else
         'armv7' }}

    node_exporter_url: >-
      https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz

    node_target: "{{ (ansible_host | default(inventory_hostname)) }}:9100"

  tasks:

    # ---------- Регистрируем target в Prometheus ----------
    - name: Render node_exporter SD file
      template:
        src: node_exporter.json.j2
        dest: /etc/prometheus/file_sd/node_exporter1.json
        owner: prometheus
        group: prometheus
        mode: "0644"
      delegate_to: 185.86.146.169
      become: yes
