---
- name: Gather target facts
  hosts: all
  gather_facts: true

- name: Generate Prometheus file_sd configs on bastion
  hosts: localhost
  gather_facts: false
  vars:
    exporters:
      - job: node_exporter
        port: 9100
        file: node_exporter.json
      - job: sql_exporter
        port: 9399
        file: sql_exporter.json
    output_dir: /etc/prometheus/file_sd

  tasks:
    - name: Collect host data from all hosts
      set_fact:
        targets_data: >-
          {{ groups['all'] | map('extract', hostvars) | map('combine', {
              'ip': hostvars[item].ansible_default_ipv4.address,
              'hostname': hostvars[item].ansible_hostname
          }) | list }}
      vars:
        item: "{{ item }}"
      loop: "{{ groups['all'] }}"
      run_once: true

    - name: Flatten targets per exporter
      set_fact:
        exporter_targets: "{{ dict(exporters | map(attribute='job') | zip(exporters | map('combine', {'targets': []}))) }}"

    - name: Fill exporter_targets with targets
      set_fact:
        exporter_targets: >-
          {{
            exporter_targets | combine(
              dict(
                exporters | map('combine', {
                  'targets': targets_data | map('combine', {
                    'targets': [ item.ip ~ ':' ~ exporter.port ],
                    'labels': {
                      'ip': item.ip,
                      'hostname': item.hostname,
                      'job': exporter.job
                    }
                  }) | list
                }) | map(attribute='job') | zip(_) | list
              ), recursive=True
            )
          }}
      loop: "{{ exporters }}"
      loop_control:
        loop_var: exporter

    - name: Render JSON files using template
      template:
        src: templates/file_sd.json.j2
        dest: "{{ output_dir }}/{{ item.value.file }}"
        owner: prometheus
        group: prometheus
        mode: '0644'
      loop: "{{ exporter_targets | dict2items }}"
